name = "Chow's Mod Pack"
author = "ZXY-CC-3ag13"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1fadc880bc3142556113b38782810a99c9f88bc679ef3120be278d0988b18e6a"

[versions]
fabric = "0.14.17"
minecraft = "1.16.5"
